export default () => ({
  theme: 'base',
  themeVariables: {
    darkMode: true,
    background: '#1a1b26',
    fontFamily: 'Inter, sans-serif',
    primaryColor: '#24283b',
    primaryTextColor: '#c0caf5',
    primaryBorderColor: '#7aa2f7',
    secondaryColor: '#2a2342',
    secondaryTextColor: '#c0caf5',
    secondaryBorderColor: '#bb9af7',
    tertiaryColor: '#1f2335',
    tertiaryTextColor: '#c0caf5',
    tertiaryBorderColor: '#565f89',
    lineColor: '#7dcfff',
    textColor: '#c0caf5',
    mainBkg: '#24283b',
    nodeBorder: '#7aa2f7',
    clusterBkg: '#1f2335',
    clusterBorder: '#3b4261',
    edgeLabelBackground: '#1a1b26',
    titleColor: '#e0af68',
    actorBkg: '#24283b',
    actorBorder: '#7aa2f7',
    actorTextColor: '#c0caf5',
    actorLineColor: '#565f89',
    signalColor: '#7dcfff',
    signalTextColor: '#c0caf5',
    labelBoxBkgColor: '#24283b',
    labelBoxBorderColor: '#bb9af7',
    labelTextColor: '#c0caf5',
    loopTextColor: '#c0caf5',
    noteBkgColor: '#3d2f1f',
    noteTextColor: '#ffd89a',
    noteBorderColor: '#e0af68',
    activationBkgColor: '#2f3549',
    activationBorderColor: '#7aa2f7',
  },
})
